### PR TITLE
WIP: add /publickey endpoint to idmtest

### PR DESCRIPTION
**Pull request by jrwren**
I need this to work and I don't know router well enough to make it work. How can I make this work?

### CODE REVIEW

**Comment by jujugui** [comment]
Merged build finished. Test FAILed.

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/identity/8/
Test FAILed.

**Comment by jujugui** [comment]
Merged build finished. Test PASSed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/identity/9/
Test PASSed.

**Comment by jujugui** [comment]
Merged build finished. Test PASSed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/identity/10/
Test PASSed.

**Comment by fabricematrat** [comment]
:+1:

**Comment by mhilton** [comment]
:+1:

**Comment by jrwren** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/identity-merge

**Comment by jujugui** [comment]
Build failed: Attempt to land pull request failed
        build url: http://ci.jujugui.org:8080/job/identity-merge/1

**Comment by fabricematrat** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/identity-merge

**Comment by jujugui** [comment]
Build failed: Attempt to land pull request failed
        build url: http://ci.jujugui.org:8080/job/identity-merge/2

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/identity-merge

**Pull request merged**
